### ISSUE TITLE
[Feature Requests] Other way(s) to delete notes, right-click, drag & drop

### ISSUE THREAD

**Issue by anazia** [standardnotes/web#129]
1. This is definitely a NTH, but it would be great to be able to delete a note using a keyboard shortcut when the note is selected in the note list. For this you might also need a visual clue (different blue in the list?) that a note is selected vs when a note is being edited. Or just a delete button when a note is selected, a bit like tags?

2. It would be nice to have a right-click menu in the note list (to delete, tag...)

3. It would also be nice to be able to drag a note into a tag

Let me know if you agree with any of these, I can help if needed.

**Comment by vitormv** [comment]
I am also interested in these features, and i can also help with coding these. =)

**Comment by mobitar** [comment]
I think keyboard shortcuts would be the next step for the desktop app, but there's a particular way of building them that will need to be explored, namely, in an extensible manner so that they are customizable, etc. Still haven't decided when this will be worked on, but it's definitely on the radar.
