### ISSUE TITLE
Unable to disable spellcheck in advanced markdown editor

### ISSUE THREAD

**Issue by wittjosiah** [standardnotes/web#149]
Nice addition of spell check in the advanced markdown editor! However, for me it seems like spellcheck is enabled by default and does not turn off when I click the spellcheck button. I was able to get it to turn off only by switching to another editor and switch back, but since I use the Advanced Markdown Editor as my default editor spellcheck seems to be enabled on all my notes by default now.

Steps to reproduce:
1) Make Advanced Markdown Editor default
2) Navigate to notes
3) Spellcheck is on and cannot be disabled

OS: macOS 10.12.6
SN Version: 1.2.6

**Comment by mobitar** [comment]
Yeah, I tried really hard to find a solution to this but I don't think it's possible. Once spell check is enabled, it plugs in deep into the core of the editor, and the only way to disable it is to reload the editor altogether. That's why the button ended up being labeled "Enable Spellcheck" and not "Toggle Spellcheck".

Reloading is one option to disable it, or as you noticed, switching notes or editors.

**Comment by mobitar** [comment]
Btw, good eye on catching that update! Forgot to make that announcement ;)

**Comment by wittjosiah** [comment]
Would it be possible to make spellcheck a separate extension or just two separate advanced editor types? I quite like the Advanced Markdown Editor but now a bunch of my notes are just covered with red highlights which are tolerable, but not super nice to look at.

**Comment by mobitar** [comment]
Oh wow, just noticed it's not disabled by default. Was supposed to be. Will make that fix.

**Comment by mobitar** [comment]
Ok, bad news. The spell check feature is poorly built. Even after enabling it, it only highlights things on the current line. So I've just removed it altogether, until I can find a better solution.

**Comment by wittjosiah** [comment]
Seems reasonable, thanks for responding so quickly to this!
