### ISSUE TITLE
Markdown editor?

### ISSUE THREAD

**Issue by lpar** [standardnotes/web#152]
The [front page README](https://github.com/standardnotes/web) says that the GPLv3-licensed web client has a Markdown editor. This doesn't seem to be the case, at least on the demo at https://app.standardnotes.org/. Is that correct?

**Comment by mobitar** [comment]
Ah that's outdated. The internal Markdown editor was removed in favor of external editors. Will update the readme now.

**Comment by BobTB** [comment]
Are these external editors (at least an simple markdown one) available for free? If not, why, and what was wrong with the internal Markdown editor to be removed?

**Comment by mobitar** [comment]
It was an architectural decision. We want to keep the base product simple and to the core so that it's easy to maintain, future-proof, and longer-lasting. By coupling, for example, Markdown directly into the codebase, we become affixed to it, and if it is no longer popular in five years, then removing it becomes an engineering challenge. By not being opinionated on the popular writing format of the time, and instead allowing plugins to be installed that suit the user, we keep the product simple while also allowing for arbitrary power.
