### ISSUE TITLE
Chrome refuses to load fonts due to Content Security Policy Violation

### ISSUE THREAD

**Issue by sancho-one** [standardnotes/web#156]
Webapp refuses to load fonts due to Content Security Policy violation. 

Webapp's settings: default theme, default editor. 
Chromium Version 60.0.3112.113 (Developer Build) Fedora Project (64-bit).

> _app.standardnotes.org/:1 Refused to load the font 'https://fonts.gstatic.com/s/lato/v13/UyBMtLsHKBKXelqf4x7VRQ.woff2' because it violates the following Content Security Policy directive: "font-src 'self'"._

It's advised as one of the possible solutions to use this meta:

`<meta http-equiv="Content-Security-Policy" content="default-src 'self'; font-src 'self' data: fonts.gstatic.com;">
`

I have to state that only Webapp is affected, Desktop app isn't.

![screenshot from 2017-10-10 14-06-52](https://user-images.githubusercontent.com/32115115/31405413-9a1d9994-adc4-11e7-8968-f76e687fb8ba.png)

**Comment by sancho-one** [comment]
@mobitar It's serious enough problem becase Chrome is the most wide-spread browser and the first experience an average new user gets with SN is throughout Web App on app.standardnotes.org.

**Comment by mobitar** [comment]
I think it's most likely a caching of one of your themes since the app doesn't use any external fonts. Try clearing your cache, or try to see what happens in an incognito window.

**Comment by sancho-one** [comment]
Well, partially the problem is solved. Indeed, clearing cache allowed
webapp to load fonts. Nevertheless, developer tools still show 16 errors of
this type.

**Comment by sancho-one** [comment]
Well, partially the problem is solved. Indeed, clearing cache allowed
webapp to load fonts. Nevertheless, developer tools still show 16 errors of
this type:

![screenshot from 2017-10-10 17-32-16](https://user-images.githubusercontent.com/32115115/31413919-2abe0404-ade1-11e7-81f1-5f38e08b40c6.png)

**Comment by DavidBiesack** [comment]
I'm seeing this same problem, even after removing all my cached data (for all time) on Google Chrome (Version 67.0.3396.99 (Official Build) (64-bit)) on Mac
When I visit https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md, all I get back is 
text/plain; charset=utf-8 application/json application/vnd.github+json application/vnd.github.v3+json application/vnd.github.v3.raw+json application/vnd.github.v3.text+json application/vnd.github.v3.html+json application/vnd.github.v3.full+json application/vnd.github.v3.diff application/vnd.github.v3.patch

and inspector shows

Refused to load the font 'data:font/woff;charset=utf-8;base64,d09GRgABAAAAAAZwABAAAAAACFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEU0lHAAAGaAAAAAgAAAAIAAAAAUdTVUIAAAZcAAAACgAAAAoAAQAAT1MvMgAAAyQAAABJAAAAYFYEU3RjbWFwAAADcAAAAEUAAACAAJThvmN2dCAAAATkAAAABAAAAAQAAAAAZnBnbQAAA7gAAACyAAABCUM+8IhnYXNwAAAGTAAAABAAAAAQABoAI2dseWYAAAFsAAABPAAAAZwcEq9taGVhZAAAAsgAAAA0AAAANgh4a91oaGVhAAADCAAAABoAAAAkCA8DRGhtdHgAAAL8AAAADAAAAAwGAACfbG9jYQAAAsAAAAAIAAAACABiATBtYXhwAAACqAAAABgAAAAgAA8ASm5hbWUAAAToAAABQgAAAlXu73sOcG9zdAAABiwAAAAeAAAAME3QpOBwcmVwAAAEbAAAAHY...JBhagk7HQzKxca2sJCE1hDt4QF+9JOS0nbaaYDCQfwCJ7Au3AHj+LO13FMmm6cl7785vven0kBjHCBhfpYuNa5Ph1c0e2Xu3jEvWG7UdPDLZ4N92nOm+EBXuAbHmIMSRMs+4aUEd4Nd3CHD8NdvOLTsA2GL8M9PODbcL+hD7C1xoaHeLJSEao0FEW14ckxC+TU8TxvsY6X0eLPmRhry2WVioLpkrbp84LLQPGI7c6sOiUzpWIWS5GzlSgUzzLBSikOPFTOXqly7rqx0Z1Q5BAIoZBSFihQYQOOBEdkCOgXTOHA07HAGjGWiIjaPZNW13/+lm6S9FT7rLHFJ6fQbkATOG1j2OFMucKJJsxIVfQORl+9Jyda6Sl1dUYhSCm1dyClfoeDve4qMYdLEbfqHf3O/AdDumsjAAB42mNgYoAAZQYjBmyAGYQZmdhL8zLdDEydARfoAqIAAAABAAMABwAKABMAB///AA8AAQAAAAAAAAAAAAAAAAABAAAAAA==' because it violates the following Content Security Policy directive: "font-src assets-cdn.github.com".

@mobitar - Would you like a new issue, or reopen this one?
