### ISSUE TITLE
Contribute.md

### ISSUE THREAD

**Issue by christiankaindl** [standardnotes/web#173]
I would love to contribute in some form to Standard Notes, but I have no idea where to start or how the project is structured. I think a CONTRIBUTE.md would be a good solution for this (and for other people in the future)

**Comment by mobitar** [comment]
Hey Christian, thanks for wanting to contribute. Totally agree that it's hard to know where to start or where everything is. That's why my next major todo is "documentation". I'll hopefully be working on that this week and try to cover every thing. This will make it easier to know where to contribute. Stay tuned..

**Comment by mobitar** [comment]
We have a bounties page now, which might be a good place to start: https://github.com/standardnotes/bounties/issues
