### ISSUE TITLE
Clip web content via Browser Extensions

### ISSUE THREAD

**Issue by lifeinchords** [standardnotes/web#177]
It would be super useful to easily save web content via browser extensions. This would mean one place to store, search and retrieve research found on the web plus standard's notes. Similar to Evernote's clipper, but just the key parts:

-  clips a web page with full formatting: HTML, CSS, images
-  ignores JS, bypassing security concerns
-  option to add one or more tags
-  works asynchronously, allowing person to continue browsing without having to wait for saving to complete

I believe Evernote parses the HTML, and injects any CSS inline into a single HTML file. Some pages don't render correctly in the Evernote app, but it does a good-enough job for most URLs. The important part is having the text and images saved, which can be indexed for search.

Maybe this would work/rely on the Plus Editor which already supports/saves the note as HTML?

If there's interest, here's a [working proof of concept Chrome extension](https://github.com/parallelsio/core-modules/tree/master/extensions/chrome/source) for a similar OSS project.

**Comment by mobitar** [comment]
Totally, this would be awesome. It's a matter of prioritization though and this one falls low on the list currently. But I do hope to explore it at some point.

**Comment by billgross** [comment]
I'd like to +1 (several times) the addition of a web clipper for Standard Notes.

I'm a long-time OneNote and Evernote user.  But I'm in the process of switching to something else because I am finding myself using Linux Mint more and more than Windows.  Neither of them support a Linux app, and as I'm frequently offline, the web interface doesn't meet the need.

Yesterday I discovered Standard Notes through Thomas Frank's YouTube channel (https://youtu.be/cDfi8BwdGvY).  SN has a Linux app *and* does all the things to keep my data safe that I've only dreamed of!  I'm giving SN a serious try.

I use the web clippers with the current note taking products I use and sure would love one for SN.  It's not a deal-breaker (I don't think), but it's a major feature desire.

Thank you!!!

**Comment by mobitar** [comment]
Hey @billgross, glad to hear you're finding promise in SN :) As an update since 2018, a web clipper is still low on the priority list. My impression is that clipping webpages tends to form really large notes, each maybe megabytes in size each. Encryption is a very close-to-the-metal process, and there's no enhancing its performance. A webclipper sounds nice, but as soon as you start to have 10-20 notes that are each 3mb clipped websites, you'll most likely notice drastic performance reductions, particularly in app startup time, and especially on mobile. For example, 10,000 notes in SN without encryption (in an offline context) might all load within a second. When you enable encryption, that time becomes much, much greater.

This is apart from the huge tangent we would need to go on to develop a browser extension, which would create a prioritization conflict in keeping the desktop, web, and mobile apps as stable as possible.

My take on this is most likely that it would be best for a 3rd party to develop this extension.

**Comment by billgross** [comment]
Thanks for your quick reply!  I really appreciate that.

I can totally see your points.  And, as a software developer myself, I would likely make the same choices on prioritization.  The web clipping feature isn't a deal breaker for me, as I said.  The big, big decider for me was that you have a Linux app.  I work in both Windows and Linux and need to have notes in both places.  Your privacy encryption made it irresistible.

Since I'm so encouraged by Standard Notes, I just jumped-in for the 5-year Enhanced deal.  I'm excited to start exploring it.

Thanks for all your work!

**Comment by mobitar** [comment]
Wow, very much appreciate your support @billgross! And glad to hear we're on the same page. Hope the app serves you well for the next five years to come 🙏

**Comment by ryanl888** [comment]
@mobitar 
> A webclipper sounds nice, but as soon as you start to have 10-20 notes that are each 3mb clipped websites 

Just wondering if something like the google keep clipper chrome extension would work better - it seems to just clip the text - 'clip selection' - and creates a new note with it.  IMO, this would also be ideal behavior for SN, thanks.

**Comment by mobitar** [comment]
Aside from the technical details, it's just important there are few core areas of code to maintain. Maintaining a web clipper takes away valuable time from maintaining the core project.
