### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by infosisio** [standardnotes/web#213]
Hello, congratulations and thanks for the amazing solution,

I just subscribed to the annual plan.

I was using boostnote for programming notes and it has this feature of allowing you to add multiple notes in one entry, and the reason behind that is that you want to group multiple code-related files/templates as part of the same entry/task.

This would make total sense to be optionally supported in standardnotes.

Think about it !

Thanks a lot !

**Comment by mobitar** [comment]
Hi @infosisio, glad to hear you're enjoying it :) That's an interesting idea. I think this could work as an editor extension in the future. For example, the Code editor can be expanded so that it would allow you to create multiple documents or code snippets in the same note. 

I'll keep this one in mind!

**Comment by mobitar** [comment]
https://github.com/standardnotes/forum/issues/245
