### ISSUE TITLE
Note History Fixes/Improvements

### ISSUE THREAD

**Issue by petermierau** [standardnotes/web#214]
I ended up changing my password several times, and then deleting and recreating an account and importing backed up files into that new account.

Two things:
When I change my password for Standard Notes account, it should offer the ability to automatically update the password for all Note Histories, since I don't remember the old password (I use a password generator).

I'm also stuck when I click on some note history items that I can't do it because the Meta data is missing or some other thing. Offer an ability in batch manager to remove notes from note history that gives that error and/or have notes in the note history with a different password removed also. (No point having you pay for dead data that a user can't even access anymore). #

**Comment by mobitar** [comment]
Yeah, I hear you. Note History is a very independent extension, and is separate from actions you may take inside the app, like changing your password. There's no language currently for server extensions to understand that a password has been changed. I'm hoping to solve this some day, but for now it's an unsolved problem.

The metadata problem relates to some history items missing metadata if they were created before a certain date. There was an update to how history items were stored, so that they know how to handle decryption if your password changes (that's when you see the "enter your old password" prompt).
