### ISSUE TITLE
How do I get the extensions running locally?

### ISSUE THREAD

**Issue by DeveloperDavo** [standardnotes/web#222]
After following https://github.com/standardnotes/web#running-locally I was able to get the app running locally (which is great!) but 
1. I couldn't figure out how to load Advanced Markdown extension https://standardnotes.org/extensions/advanced-markdown. 
2. Also, isn't setting `SF_DEFAULT_SERVER=https://sync.myserver` supposed to prevent 'Account' from popping up?

**Comment by mobitar** [comment]
You'd need to host each extension yourself. They don't automatically come with the web app. The extensions are separately located [here](https://github.com/sn-extensions/).

Setting the default server won't disable the Account auto-popup. However, I have it on my todo to disable it from popping up again after its closed. The idea was to deter people from using the app fully offline, as it's really not recommended unless you really know what you're doing and keep proper data backups. But I've since learned that a lot of people still do use it offline.
