### ISSUE TITLE
Firefox gives error popup on opening

### ISSUE THREAD

**Issue by ragymorkos** [standardnotes/web#240]
I always leave Standard Notes open in a tab on Firefox on Ubuntu, and every time I close Firefox and open it again, I get the following popup from the Standard Notes tab when it first loads:

![screenshot from 2018-09-19 17-16-30](https://user-images.githubusercontent.com/23442184/45854246-14c32c00-bd18-11e8-9de3-4cc679ab374b.png)

The only way it would go away is by refreshing the Standard Notes page. This bug is specific to Firefox; Chrome doesn't have the same problem.

**Comment by mobitar** [comment]
Hey @ragymorkos, can you describe specific reproduction steps? I tried to simulate it based on the limited details but couldn't replicate. If you could provide step by step replication instructions that would be helpful.

**Comment by ragymorkos** [comment]
Thanks for the quick reply! It has been occurring for a while, but I haven't signed out before. I have signed out and in again for testing, and now it doesn't appear. I'm going to close this issue till I can narrow down exactly what conditions cause it and how you can replicate it on your machine. Once I am able to do so, I will reopen this issue again.

**Comment by mobitar** [comment]
Ok thanks!

**Comment by Daniel-Kalus** [comment]
I have the exact same issue, and it has been present since I started using Standard Notes in January.
The popup text says: "The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note."
Logging out and in again doesn't resolve the issue.

**Steps to reproduce:**

1. Have Standard Notes as a pinned tab in Firefox
2. Start Firefox

If I close Firefox and the start it again after a short time, the popup will not appear. But if I have it closed for maybe an hour or so (or shorter), the popup will appear.
After dismissing the popup, it says "Saving..." in the top right. I can click on all my notes, but they won't be displayed, the right part of the page stays white. Everything works normally after reloading the page.

I tried this with a clean firefox profile without addons or modifications -> same problem.

**Comment by mobitar** [comment]
@Daniel-Kalus thanks for the report. Do you also see an empty interface, similar to @ragymorkos's screenshot? That is, no data is loaded, and that alert just appears.

**Comment by Daniel-Kalus** [comment]
Sorry for the late reply.
It varies, sometimes I can see my notes listed but they don't show up on the right side when clicking on them. Sometimes the whole interface is empty, as seen in the screenshot of the first post.

Like the user in the referenced post, I get this issue definetely every morning when I first start firefox, or if I had it closed for some time. When I reload the tab to fix the issue, then close and restart firefox in a short amount of time, there is no popup.

**Comment by mobitar** [comment]
Ok thanks, will need to figure out what's going on here. I was able to replicate it once but no more: https://github.com/standardnotes/forum/issues/546#issuecomment-490492696
