### ISSUE TITLE
Disable FileSafe in Editor by default

### ISSUE THREAD

**Issue by mfa777** [standardnotes/web#244]
I found it is necessary to have an option for Enable/Disable FileSafe in Editor by default.
Note every note need files. But now FileSafe is enable by default and it took big screen space.
I have to disable it before writting the content.

![image](https://user-images.githubusercontent.com/2765931/46604697-bd032e00-cb29-11e8-9a86-951e7ea6a083.png)

**Comment by mobitar** [comment]
We would like to add an option to disable extensions by default, and make exceptions per note. Currently, only the opposite is handled: enabled by default, disabled per note.

For now, there are two things you can do:

1. Disable it globally from the Extensions menu.
2. Set up keys and integrations for your FileSafe so that it takes less vertical space. When you do that, it will reduce it's height in half.
