### ISSUE TITLE
[Suggestion] QoL When Re-Focusing Application

### ISSUE THREAD

**Issue by jakemingolla** [standardnotes/web#278]
Apologies in advance if I'm not following the correct contributing guidelines (or am in the wrong place), I didn't see a `CONTRIBUTING.md` in the repo.

The following portions of Standard Notes are somewhat annoying when re-focusing the application after it has locked:
- The passcode field has to be clicked into before the code can be entered
- Any tag filters applied to the list of notes is not maintained

I know these are relatively minor but they would make a big difference when managing a mixture of personal and professional notes in the workplace.

Standard Notes Version 3.0.5 (3.0.5)
Mac OSX El Capitan 10.11.6 (15G22010)

**Comment by mobitar** [comment]
Hey @jakemingolla, thanks for the feedback. I can confirm that I'm also seeing the passcode focus issue. We'll have this one fixed in an upcoming release. As for preserving app state (like tag and note selection), I do agree this would be useful, but this is a more involved feature. I'll keep that one in mind, but no definite timeline on that.

**Comment by mobitar** [comment]
Passcode autofocus is fixed in 7b4e9d57af8df47924428063de2dbdf6265ab022. Part of upcoming 3.0.7 release.
