### ISSUE TITLE
Tags not properly aligned in latest release

### ISSUE THREAD

**Issue by mobitar** [standardnotes/web#316]
![image](https://user-images.githubusercontent.com/3277844/66932045-a1641a80-effc-11e9-9a47-70705cbb2895.png)

**Comment by bryvin** [comment]
You probably know already but it's due the `justify-content: space-between` found here in a recent commit: https://github.com/standardnotes/web/commit/0a8bc98725454abf4a6f985b72c829772bd9638c#diff-b62887c90895c981f5e99e5c09e7b529R59

The problem is the count on the right side is sometimes larger (more digits) which changes the spacing.

**Comment by mobitar** [comment]
@bryvin yup, good catch, thanks.
