### ISSUE TITLE
Futura theme doesn't work

### ISSUE THREAD

**Issue by Teoxoy** [standardnotes/web#331]
The Futura theme doesn't work in the browser app but it works fine in the windows app.

**Comment by bryvin** [comment]
I just tested and all the themes are currently working for me, which browser are you using? Also can you try re-installing the theme and reporting back if that solved it or not?

If it didn't solve it, can you check out the console for your browser and let us know if there are any errors when you try activating Futura?

**Comment by Teoxoy** [comment]
Looks like I fixed it by reinstalling from the browser and it now works fine.

How it happened:
1. I created an account
2. I logged into the web app
3. I closed the web app
4. I upgraded to Extended
5. Downloaded the windows app
6. Setup extensions + Futura in the windows app
7. I opened the web app and Futura was enabled and installed (according to the extensions panel)

Switching the Futura theme on and off didn't fix it but reinstalling it did.
Maybe you can reproduce it.

**Comment by bryvin** [comment]
I gave this a shot (using incognito though..) and was unable to reproduce this. In the past and based on my testing this sounds like it was most likely a caching issue with the web browser and uninstalling and reinstalling will clear a cache issue. If you experience this again please report back here.

Welcome to Standard Notes Extended otherwise! :)

**Comment by Teoxoy** [comment]
Might be, I will close this for now.

> Welcome to Standard Notes Extended otherwise! :)

Thanks! :)
