### ISSUE TITLE
Switching between editors is quite slow

### ISSUE THREAD

**Issue by Teoxoy** [standardnotes/web#332]
Switching between editors is quite slow.

I think that's fine for the first time the editor is loaded but subsequent editor switches should be nearly instant.

I checked the network tab and it looks like this is because the app refetches all the editor components.

**Comment by bryvin** [comment]
The web app does fetch the editor with each change of note, this is because browsers are not able to read files off of the users system for security reasons. However on the desktop app it does download the editors to your local machine and hosts them for the app to fetch locally; which should ultimately be pretty close to instant. Then the local files get re-downloaded when a new version of that editor becomes available.

**Comment by Teoxoy** [comment]
Can't the editors be cached in memory?
That should improve the load time of editors on the web app .

**Comment by bryvin** [comment]
My apologies, I was slightly mistaken. Browser caching does take effect but only for the editor's resources (images, js, css, etc). The main file of the editor that contains the HTML is requested each time but is cached on the server side. It may be possible to make some additional improvements here in the future.
