### ISSUE TITLE
Autolock timer doesn't reset when tab regains focus

### ISSUE THREAD

**Issue by BowenYin** [standardnotes/web#406]
(Bug report for web version)
I currently have a 1 minute autolock timer set. It says in the settings panel that the timer starts when the page loses focus, but if I switch back to it, the timer doesn't reset. For example, if I switch to a different tab for 55 seconds and then switch back to Standard Notes, it locks in 5 seconds even if I'm viewing it with the tab focused. This gets pretty annoying sometimes.

 - OS: Chrome OS
 - Browser: Chrome
 - Version: 81.0.4044.141

**Comment by BowenYin** [comment]
Any idea on when this will get fixed? Just wondering :)

**Comment by JaspalSuri** [comment]
Currently the team is still working on the refactor where a lot of under-the-hood improvements are being made. If this bug is still reproducible afterwards, then we'll schedule it within the list of remaining bugs to fix! No ETA on when the refactor will be complete, but it's what everyone on the dev team is working on. 

That said, I don't know what Baptiste might have tested so far. :)

**Comment by baptiste-grob** [comment]
Yes sorry about this, I understand it's a pretty inconvenient issue. We're a little choked up in terms of resources at the moment but we'll definitely get around to it.

**Comment by baptiste-grob** [comment]
Hey there, this problem is now fixed thanks to https://github.com/standardnotes/web/commit/9036beb3f370a95c2d190754bd1009658c01cdeb. It will be deployed to the web app momentarily and included in the next version of the desktop app 👍
