### ISSUE TITLE
Not working properly on Palemoon Browser

### ISSUE THREAD

**Issue by CalibSerrano** [standardnotes/web#447]
**Describe the bug**
It seems like standard notes web interface does not support my preferred browser, Palemoon 28.11.0
When I sign in my account it just keep loading and not signing in.
It works when I reload the page. But it has another issue, it cannot sync my new notes, it just keep "syncing..". Then when I reload the page, my account was sign out.

**Desktop (please complete the following information):**
 - OS: Debian Sid
 - Browser Palemoon 28.11.0

**Comment by JaspalSuri** [comment]
Hi, thanks for bringing this to our attention. Since this has been reported via issue #400, I'm going to close this thread. Let me know if you have any other questions! I've responded to your [post on reddit](https://www.reddit.com/r/StandardNotes/comments/i5q6jm/not_working_properly_on_palemoon_browser/) as well.
