### ISSUE TITLE
Please don't specify a bad quality Chinese font

### ISSUE THREAD

**Issue by ghost** [standardnotes/web#470]
Please do not use "Microsoft Yahei" and "微软雅黑体" in --sn-stylekit-simplified-chinese-font.
These fonts are of low quality and very dirty.

In addition, please do not specify a Chinese font when displaying Japanese.

**Comment by JaspalSuri** [comment]
Hi @gif-byte,

Thank you for the feedback!

> Please do not use "Microsoft Yahei" and "微软雅黑体" in --sn-stylekit-simplified-chinese-font.

What would you suggest that we use instead? We would be open to viable alternatives. 

> In addition, please do not specify a Chinese font when displaying Japanese.

Can you tell me where this occurs or what this specifically relates to?

**Comment by gif-byte** [comment]
> What would you suggest that we use instead? We would be open to viable alternatives.

Why not leave it to the user's settings without specifying the font?


> Can you tell me where this occurs or what this specifically relates to?

It is as follows.

OS: Windows 8.1 x64 Japanese
Browser: Firefox 80.0.1 x64 Japanese

**Comment by baptiste-grob** [comment]
Hey @gif-byte, what do you mean by "user's settings"? Browser defaults? For Latin languages the default fonts tend to not look good, which is why we specify fonts ourselves. We'd like to let users customize their font at some point but we're not there yet.

**Comment by gif-byte** [comment]
> Hey @gif-byte, what do you mean by "user's settings"? Browser defaults? For Latin languages the default fonts tend to not look good, which is why we specify fonts ourselves. We'd like to let users customize their font at some point but we're not there yet.

I'm not sure about the Latin language, but please stop specifying poor quality Chinese fonts.

Stop applying that poor quality font to Japanese as well as Chinese.

**Comment by gif-byte** [comment]
User settings are browser settings.
I think you can specify the font that the user likes.

**Comment by mobitar** [comment]
Hmm, [this user](https://github.com/standardnotes/desktop/issues/340) was telling us that MS Yahei is the _good_ font, compared to SimSun.

**Comment by gif-byte** [comment]
Let's separate the two issues.

1.  Is it appropriate to use Microsoft Yahei for Chinese display and
2.  Whether Chinese fonts such as Microsoft Yahei should be used for Japanese display or not.

Aside from the first, the second is a very bad thing. It should definitely be changed.

**Comment by gif-byte** [comment]
However, I think Microsoft Yahei is as dirty as bitmap fonts.
https://imgur.com/a/9m5WuqC

**Comment by LER0ever** [comment]
> However, I think Microsoft Yahei is as dirty as bitmap fonts.
> ![2P6QXPf](https://user-images.githubusercontent.com/70895227/93187695-0c712080-f77b-11ea-826f-424cceafa519.png)

I don't think that's Microsoft Yahei just by looking at it, that's more like SimSun, which is the fallback bitmap font mentioned in the issue commented by @mobitar. Here a comparison of the mentioned fonts:

<img width="1013" alt="List of the mentioned fonts" src="https://user-images.githubusercontent.com/10568668/96860933-fb13e600-1495-11eb-8ba3-d1e542bd7e0d.png">

In general, unlike latin-family fonts,  it's not possible to bundle the entire Chinese font due to large size , so MS Yahei is usually selected as the fall-back font so that Windows users get a decent system font. The rule is to at least end up with a sans-serif Chinese font (黑体).

On macOS, it will either use MS Yahei if present in the system, or fall back to Ping Fang SC which also looks nice. In my case it uses the system MS Yahei.

As for Japanese fonts, for Japanese who don't have MS Yahei Chinese font installed, a Japanese sans-serif font will be selected. So I don't see any problem here.

Just passing by while browsing the issue list... but I think we should be fine closing this one. OP is **ghost**-ed anyway...

**Comment by baptiste-grob** [comment]
Thanks for the valuable insight @LER0ever 😊 I'll be closing this one.
