### ISSUE TITLE
Is it possible to disable WebAssembly?

### ISSUE THREAD

**Issue by bitpixl** [standardnotes/web#541]
Hi,

I've just started using Standard Notes and the main reason for me is the encryption (security).

However, I found out that in order to use the web-based version (I'm using firefox), webassembly needs to be enabled.
Webassembly (sadly) does come with increased security risks. Please see the following link for some examples and more info: 
https://github.com/arkenfox/user.js/issues/1037#issuecomment-708092814

Would you maybe consider adjusting the Standard Notes (web) version (if possible), so that it also functions for us folks that have webassembly disabled out of security concerns?

thank you for reading and keep up the great work!

**Comment by JaspalSuri** [comment]
Hi @bitpixl, 

Thanks for the kind words! I'll reach out to the dev team and someone will get back to you. 🙂

**Comment by baptiste-grob** [comment]
Hey @bitpixl, we use [libsodium](https://github.com/standardnotes/sncrypto/blob/004/packages/web/package.json#L21) to encrypt and decrypt your data, which relies on WebAssembly to perform these operations at a reasonable speed, so disabling it is unfortunately not an option for us.

Your concerns are certainly not unwarranted though. I think the best solution here would be for browsers to let users allow/deny WebAssembly usage on a per-site basis, rather than globally…

**Comment by mobitar** [comment]
Or we wait until WebCrypto adds support for XChaCha20-Poly1305 and Argon2. These are becoming more commonplace to replace AES-GCM and PBKDF2, respectively, and more and more platforms are adding native support for them.

**Comment by bitpixl** [comment]
I appreciate looking into it and providing me an answer, eventho it wasn't the one I was hoping for ;)
For now I guess the only solution is to setup a seperate firefox profile that has webassembly enabled or just use the app.
