### ISSUE TITLE
[Feature Request] Trash Bin

### ISSUE THREAD

**Issue by levlaz** [standardnotes/web#56]
When I delete a note, I would rather have it be marked as `is_deleted` and show up in a Trash bin than actually be deleted. 

**Justification**:
* It is cheap to store text, it is expensive to accidentally lose an important note 

There should also be an option to actually delete something out of the trash bin, and an option to completely empty the trash.

**Comment by mobitar** [comment]
Perhaps an "Archive" menu item that simply removes all tags from the note and adds the "archive" tag? Then "All" would hide "Archive" tags. But let's sleep on this. Every new line of code scares me and threatens sustainability. Whatever can be done manually by the user, the better.

**Comment by mobitar** [comment]
Because then you'd have to add another button for "Clear Archive". I think a good solution would just be for the user to manually replace all tags with "#archive". Then if you want to clear the archive, you can just delete the individual notes. 

SN requires users to adopt to a lifestyle just a little less lavish than what normal "startup" software provides. The norm is to do whatever it takes to make the experience flawless, but we've seen where that gets us: bloated, expensive, and non-sustainable software that eats your data. 

When you start eating healthy, you'll miss the easy, convenient, and delicious junk food. But it's clear which one leads to a longer and happier life ;)
