### ISSUE TITLE
Search by tag

### ISSUE THREAD

**Issue by emiola** [standardnotes/web#64]
I'm not sure if this is already implemented or in the backlog, but I believe it's a key feature. 

Thank you so much for this minimalistic and safe approach to note taking.

**Comment by mobitar** [comment]
Do you mean searching a particular tag for notes? Or do you mean searching for a tag?

**Comment by emiola** [comment]
The first one. And I was thinking about the desktop client, but just realized I'm in the web repo. Sorry for that.

**Comment by mobitar** [comment]
You can already do that. Just select the tag from the left, then enter a search query in the middle column.

**Comment by emiola** [comment]
Oh well. Fantastic. Just a click away! Thank you. 

So, what about the second feature, a search box also for the tags (I've imported all my notes from evernote and I have plenty of them).

**Comment by mobitar** [comment]
How many tags do you have?

**Comment by emiola** [comment]
Too many! 1800

**Comment by mobitar** [comment]
1800 tags?? What is wrong with you people 😖 Please explain to me how you went about having 1800 tags. How many notes do you have?

**Comment by emiola** [comment]
Ahah :-) Nooo, I apologize, 1800 are the notes and about 220 the tags! You know, they are notes cumulated in years of consistent note taking.

**Comment by emiola** [comment]
I should maybe add that they are also multilingual... But, this is just to say that I take a lot of notes in whatever language I feel, but not to suggest further features to add. I'd like to keep all simple as it is.

**Comment by mobitar** [comment]
Lol ok cool. You made me feel crazy for a second. A search bar is reasonable for tags then. Will add it to the list.

**Comment by anavarre** [comment]
I have a similar use case. Take this scenario:

- Thousands of notes
- Hundreds of tags
- You want to search for, e.g. node.js installation

Easy, you could simply select the `node.js` tag and find the related note via the search bar. Problem is, perhaps the way you _think_ and thus store notes is different. The `node.js` tag might be the datastore for everything related to developing with node.js - And then your note might be flagged with the `sysadmin` tag instead, because in the note explaining how to install node.js you might also have tips and tricks on how to tune it for best performances, etc. It would thus not really be a note about node.js per se but on app performance and maintenance above all.

This is a subtle but important difference IMHO. You would thus expect to be able to a) filter out by tags and b) restrict the search to those tags only.

Usually what happens is in the search bar you type `#tag1 #tag2 #tag3 <search_string>`

**Comment by mobitar** [comment]
Thanks for the feedback. Definitely hope to make search stronger in the near future.

**Comment by mobitar** [comment]
Grouping into https://github.com/standardnotes/web/issues/191
