### ISSUE TITLE
Add password confirmation for registration

### ISSUE THREAD

**Issue by mobitar** [standardnotes/web#68]
When a user clicks the "Register" button, app should present a password confirmation box under the password box with a small note about how important it is they don't forget their password. Then it will have a confirm button that actually submits the registration. This is how the iOS app handles it.

**Comment by albertocoronado** [comment]
Quick question! I didn't wanted to add another issue. I created my account recently because I wanted to try it out, however I would like to change my password, is that possible or how do I go about it? I saw that my encryption key depends on my password so I am assuming I would have to delete everything to make a new one? Thanks.

**Comment by mobitar** [comment]
@albertocoronado I'm actually working on change password functionality now. It will require re-encrypting all your notes and syncing them back with the server. No need to delete everything. Will post a message here when it's ready.

**Comment by mobitar** [comment]
@albertocoronado ok pw change functionality is now up. Give it a try (download backup beforehand if you have important data)

**Comment by albertocoronado** [comment]
Were you working on it before I asked? That was extremely fast. I already tried it, works great!

**Comment by albertocoronado** [comment]
I already tried it, works great! Doesn't feel like a "beta" to me.

**Comment by mobitar** [comment]
Glad to hear it worked. I started on it this morning. Your initial comment was a good reminder :)
