### ISSUE TITLE
Is the Extension manager going to be removed?

### ISSUE THREAD

**Issue by dec0dOS** [standardnotes/web#713]
Hello, Standard Notes team!

I want to ask why the extension manager has been removed from the codebase?
I have some projects around the SN, the most interesting one was is to provide a community-managed Extensions store. Currently, it is in a closed beta, but it works great. It provides an alternative to the current extensions workflow, so it makes the development and deployment of the extensions a much easier process. It also scrapes all of the community extensions from GitHub, to make the installation and exploration of the new extensions from the Extension manager.  

Is the Extension manager is going to be removed? So, I suppose that there will be no way to fully self-host the Standard Notes afterward.

**Comment by mobitar** [comment]
We're removing the Extensions Manager itself in favor of native extension handling (moving to Preferences essentially).

The app store model is a cool idea, but to be honest we've had the extensions manager around for probably 4 years and that concept never came to fruition. I think there are a lot of prerequisites necessary before the app store model makes sense.

In the new preferences pane, the concept of a repository will no longer exist, but you can still install 3rd party extensions individually. So you could still build an app store, but the listing of extensions will have to be external.

**Comment by dec0dOS** [comment]
Hello, @mobitar!
Thanks for the detailed explanation!


I'm a little bit upset because the Extension Store concept was based primarily on the Extension manager. All the extensions could be downloaded from the Standard Notes Extensions tab without using external resources (after adding the new repo, of course).

Could you tell please how will be the native extension manager different from the old one?

**Comment by mobitar** [comment]
> Could you tell please how will be the native extension manager different from the old one?

Will be mostly the same, but will be native. We're trying to rely less on using extensions for core functionality (thus removing Batch Manager a few months ago, and now removing Extensions Manager, which itself is an extension.)

**Comment by jmason888** [comment]
> thus removing Batch Manager a few months ago

As a power user, I occasionally rely on Batch Manager to do various cleanups of my notes database, as well as a more fine-grained restore from backups than the current interface provides.  Do I need to maintain my own fork in order to do this, or will there be some way to enable "expert mode" for this?

**Comment by jmason888** [comment]
I guess the "Backups Explorer" is the most critical piece of the Batch Manager for me, but this seems to be a repeat of the earlier trend (e.g, with the Plus editor and custom JavaScript) of "dumbing down" the interface without leaving an escape-valve for power users.  I would have hoped the team would have learned from past comments that there is a significant userbase of power users here, that's _why we use StandardNotes_, and if you are going to "simplify" something and remove functionality, please be sure to allow an "advanced settings" way for us to get it back.  Promising replacement functionality for the future isn't good enough: we had (and relied upon) existing functionality, which could easily be made available.

**Comment by ashutoshsaboo** [comment]
+1^, slightly saddened as SN could have possibly bare-minimum communicated users in advance of this change of deprecating extension manager. Existing users self hosting SN would be almost directly impacted now after discovering this. @moughxyz

**Comment by moughxyz** [comment]
The concept of a repository is deprecated in the new architecture. However you can still install individual extensions. The reason is that repositories had no real use case for us with the new architecture, and the only 3rd party use case they had was hosting all of our extensions wholesale. You can still do the latter (for extensions with an appropriate redistribution license), but they would need to be installed one by one.

The dream with repositories originally was that we'd have bustling third party app stores for extensions, but this never came to fruition. Instead people used repositories to just clone our legacy Extended infrastructure.

**Comment by dec0dOS** [comment]
As a long-term Standard Notes user with multiple Extended subscriptions, I really appreciate SN's team work. Although, that is the first change in SN that I dislike as an advanced user. The old Extension manager was much more intuitive to use, with better UI and useful features like Extension picture preview, Batch manager, and repositories support. Current extension management is far worse than before.

One more important comment: to open up the Extension manager, you have to click 4x times more!

**Comment by moughxyz** [comment]
We're moving away from Extensions in general. The main thing we've learned over the past several years is that users are confused by extensions. They just want things to work out of the box. This is why in the new system once you sign up for a plan, you don't have to do anything. Editors just appear. They feel like more like features than extensions. So that's the goal.

In a few months Folders will also become a native feature, then several months later Files will become a native feature. At that point the only extensions that will remain are editors. And so the extensions infrastructure will only focus on editors.

**Comment by dec0dOS** [comment]
That is sad. I understand that to scale well, you have to simplify the UI for the new users. I think that is there a better way than losing the ability to customize and to provide rich modifications to SN client without the recompilation. I was hooked by this idea, that I could add some features to the product that I love using the accurate API. And now, the SN has to deviate from the original ideas and principles and remove the great feature that power users love.

It would be awesome if it could be possible to provide the advanced mode for SN with the Extension Manager.

**Comment by ashutoshsaboo** [comment]
Moving forward, for self hosting users of SN would they get the folders/files feature out of the box? Or would they also have to mandatorily subscribe to SN subscription to use those? Could you help clarify @moughxyz ?

**Comment by moughxyz** [comment]
The architecture is all open-source, so anything we could do theoretically a self-hoster would be able to do as well. The way we do it is that clients check for a subscription and if that subscription is entitled to particular features. So self-hosters would have to modify their DB to give themselves a subscription. But I haven't tested this flow.

**Comment by ashutoshsaboo** [comment]
Hmm, I was rather thinking since extensions are supposed to be client side - so let's say even after you made those as native features, if after that someone installed the same files/folder extension would that be hard blocked by some way (or is there any separate architecture change being done to block these extensions automatically on the client moving forward?) on the client side by SN moving forward? Or would those extensions still continue to work if someone installs them manually, thus being backwards compatible? @moughxyz

**Comment by moughxyz** [comment]
It's just that the ability to display an extension for where Folders live will be removed. So there will be no logic to encapsulate a folders extension. The only extensible area of the app will be themes + editors. You might say "why not just keep it in case developers want to create custom extensions for folders"—the answer is that this architecture will be unmaintained and unprioritized and will be dead code for us. So it's not an option.
