### ISSUE TITLE
[Bug] Inserting tab into existing note no longer works

### ISSUE THREAD

**Issue by djhalliday** [standardnotes/web#79]
Seems to be a regression introduced in latest (0.2.4)

**Comment by mobitar** [comment]
This was removed as the Markdown editor was removed. Instead, custom editor functionality should be handled by Editor extensions. Because if we add tab to plain editor, where do we draw the line? I know it's inconvenient, but it's the best decision to make for the future.

I'd recommend adding the Simple Markdown Editor: https://standardnotes.org/extensions/simple-markdown

It doesn't have tab support yet, but that's next on my list.

**Comment by djhalliday** [comment]
Got it. Thanks!
