### ISSUE TITLE
Saving Changes While Typing - Moves Cursor

### ISSUE THREAD

**Issue by sneakysnook** [standardnotes/web#9]
When editing or typing not at the lowest point of the note, auto saving interrupts typing and pushes the cursor to furthest point of the note.

**Comment by mobitar** [comment]
Hey, thanks for sending this in. I can't seem to replicate this. Can you tell me what browser and operating system you're using? Also can you send a screenshot of the note so I can get a sense of its length? (A screen recording would be great :)

**Comment by sneakysnook** [comment]
Sorry for the slow response, took a few tries to get it happen again and then get the recording down to size and formatted.

[sn.zip](https://github.com/standardnotes/web/files/681618/sn.zip)

Chrome Version 55.0.2883.87 m (64-bit)
Windows 10

**Comment by mobitar** [comment]
Wow, this is great, thanks. Interesting bug. I'm going to see if I can replicate this.

**Comment by mobitar** [comment]
This issue has been fixed. Thanks for reporting this in. 

The issue was a very difficult to reproduce sync conflict. (I had to sync 100 times per second to replicate it)

What will happen now in the case of conflicts is that the one you just saved takes precedence, and the conflicted one is duplicated and sent back as a new note.
